# Generated by Django 2.0.2 on 2018-06-22 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('location', models.CharField(max_length=50)),
                ('ev', models.CharField(max_length=50, verbose_name='Событие')),
                ('comanda_in', models.CharField(max_length=50)),
                ('photo_in', models.ImageField(blank=True, null=True, upload_to='images')),
                ('result_in', models.IntegerField(blank=True, verbose_name='Положили')),
                ('result_out', models.IntegerField(blank=True, verbose_name='Занесли')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='images', verbose_name='Фото')),
                ('source', models.URLField(blank=True, verbose_name='Источник')),
                ('pub_date', models.CharField(max_length=12, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Pararaph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=8000)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rk_dgtu.News')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images')),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rk_dgtu.Albom')),
            ],
        ),
    ]
